a=input ('Stage 1 of human development:')
b=input ('Stage 2 of human development:')
c=input ('Stage 3 of human development:')
d=input ('Stage 4 of human development:')
e=input ('Stage 5 of human development:')
f=input ('Stage 6 of human development:')
g=input ('Stage 7 of human development:')
print (a,b,c,d,e,f,g, sep='=> ')
